### ISSUE TITLE
Wrap external network communication components in an error boundary component

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/structured-metadata-editor-react#31]
### Description
When network issues pop up accessing external JSON data, the app should not completely fail.  Need to wrap in a React error boundary to handle gracefully.

### Done Looks Like
- On network data errors, the app fails gracefully and provides a reasonable error message to the user.

### Tasks
- [ ] Create an error boundary component for network communication
- [ ] Wrap existing network communications
- [ ] Handle error messaging display to user
