### ISSUE TITLE
Create a packaging yarn script to isolate only files needed to create the npm package

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/structured-metadata-editor-react#84]
### Description
Instead of manually copying files, need a yarn script which will copy over only the necessary files to drop into the packaging repository.  

### Done Looks Like
- A simple script is created and copies all needed files to a directory.

### Tasks
- [x] Investigate configuring webpack within create-react-app
- [x] Look into alternate npm packages to do copying/cleaning
- [x] Create the script
- [x] Test script

**Comment by adamjarling** [comment]
@Dananji @cjcolvar fyi

https://github.com/avalonmediasystem/structured-metadata-editor-react/wiki/Packaging-the-module-for-export

**Comment by cjcolvar** [comment]
FWIW it looks like some angular packages take an approach of building the release as a new tag within the development repo:
https://github.com/angular/material2/blob/master/scripts/deploy/publish-build-artifacts.sh
I wonder if that approach would be simpler or cleaner or neither.
